//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDStat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PDStat.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;ワールドイズマイン&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Waarudo Izu Main&quot;,
        ///		&quot;ENTitle&quot;: &quot;World Is Mine&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;ひねくれ者&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Hinekure Mono&quot;,
        ///		&quot;ENTitle&quot;: &quot;The Rebel&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;恋は戦争&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Koi wa Sensou&quot;,
        ///		&quot;ENTitle&quot;: &quot;Love is War&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;その一秒スローモーション&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Sono Ichibyuo Slow Motion&quot;,
        ///		&quot;ENTitle&quot;: &quot;That One Second Slow Motion&quot;
        ///	},
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PD1Songs {
            get {
                return ResourceManager.GetString("PD1Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;Mode&quot;: &quot;Tutorial&quot;,
        ///		&quot;JPTitle&quot;: &quot;Ievan Polkka&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;ロミオとシンデレラ&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Romeo to Cinderella&quot;,
        ///		&quot;ENTitle&quot;: &quot;Romeo and Cinderella&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;magnet&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;愛言葉&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Ai Kotoba&quot;,
        ///		&quot;ENTitle&quot;: &quot;Love Words&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;サウンド&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;sound&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;ココロ&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Koko [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PD2Songs {
            get {
                return ResourceManager.GetString("PD2Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;Mode&quot;: &quot;Tutorial&quot;,
        ///		&quot;JPTitle&quot;: &quot;Ievan Polkka&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Tutorial&quot;,
        ///		&quot;JPTitle&quot;: &quot;Ievan Polkka (Extreme)&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;メルト&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Melt&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;アカツキアライヴァル&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Akatsuki Arrival&quot;,
        ///		&quot;ENTitle&quot;: &quot;Daybreak Arrival&quot;,
        ///		&quot;LocalizedTitle&quot;: &quot;Akatsuki Arrival&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;packaged&quot;,
        ///		&quot;LocalizedTitle&quot;: &quot;Packaged&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PDF2Songs {
            get {
                return ResourceManager.GetString("PDF2Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;Mode&quot;: &quot;Tutorial&quot;,
        ///		&quot;JPTitle&quot;: &quot;Ievan Polkka&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;キャットフード&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Cat Food&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;秘密警察&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Himitsu Keisatsu&quot;,
        ///		&quot;ENTitle&quot;: &quot;Secret Police&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;メランコリック&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Melancholic&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;Weekender Girl&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;タイムマシン&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Time Machine&quot;
        ///	},
        ///	{
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PDFSongs {
            get {
                return ResourceManager.GetString("PDFSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;Mode&quot;: &quot;Tutorial&quot;,
        ///		&quot;JPTitle&quot;: &quot;Ievan Polkka&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;ねこみみスイッチ&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Nekomimi Switch&quot;,
        ///		&quot;ENTitle&quot;: &quot;Cat Ears Switch&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;孤独の果て&quot;,
        ///		&quot;RomajiTitle&quot;: &quot;Kodoku no Hate&quot;,
        ///		&quot;ENTitle&quot;: &quot;End of Solitude&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;Palette&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;SPiCa -39&apos;s Giving Day Edition-&quot;
        ///	},
        ///	{
        ///		&quot;Mode&quot;: &quot;Default&quot;,
        ///		&quot;JPTitle&quot;: &quot;Starduster&quot;
        ///	},
        ///	{
        ///		&quot;M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PDXSongs {
            get {
                return ResourceManager.GetString("PDXSongs", resourceCulture);
            }
        }
    }
}
